channelAplication/Controllers/channelController.cs
using channelAplication.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace channelAplication.Controllers
{
    public class channelController : Controller
    {
        private DefaultConnection db = new DefaultConnection();
        // GET: channel
        public ActionResult Index()
        {
            return View();
        }


        public ActionResult channel()
        {
            return View(db.Channels.ToList());
        }


        [HttpPost]
        public ActionResult channel(string searchterm)
        {
            using (DefaultConnection db = new DefaultConnection())
            {
                if (string.IsNullOrEmpty(searchterm))
                    return View(db.Channels.ToList());
                else
                    return View(db.Channels.Where(x => x.chanName_En.ToLower().Contains(searchterm.ToLower())).ToList());
            }

        }

        public JsonResult searchchannel(string term)
        {
            List<string> channel = new List<string>();
            using (DefaultConnection db = new DefaultConnection())
            {

                channel=db.Channels.Where(x => x.chanName_En.ToLower().Contains(term.ToLower())).Select(y=>y.chanName_En).ToList();

            }
            return Json(channel, JsonRequestBehavior.AllowGet);
        }




        public ActionResult category()
        {
            return View(db.Categories.ToList());
        }

        public ActionResult Satellite()
        {
            return View(db.Satellites_.ToList());
        }

    }
}

channelAplication/Views/sherd/_MainMenu.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>

    <meta name="keywords" content="" />
    <meta name="description" content="" />
    <!--

    Urbanic Template

    http://www.templatemo.com/tm-395-urbanic

    -->
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!--<link rel="shortcut icon" href="PUT YOUR FAVICON HERE">-->
    <!-- Google Web Font Embed_______________________________________________________________________________ -->

    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
    <link href='@Url.Content("~/Content/mystyle/")http://fonts.googleapis.com/css?family=Lato:100,300,400,700,900' rel='stylesheet' type='text/css'>
    <link href="@Url.Content("~/Content/mystyle/")css/style.css" rel="stylesheet" type="text/css" media="all" />
    <link rel="stylesheet" type="text/css" href="@Url.Content("~/Content/mystyle/")css/imgeffect.css" />
    <link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">


    <!-- Google Web Font Embed______________________________________________________________________________________ -->

    <link href='http://fonts.googleapis.com/css?family=Open+Sans:400,300,300italic,400italic,600,600italic,700,700italic,800,800italic' rel='stylesheet' type='text/css'>

    <!-- Bootstrap core CSS -->
    <link href="@Url.Content("~/Content/mystyle/")css/bootstrap.css" rel='stylesheet' type='text/css'>

    <!-- Custom styles for this template -->
  
    <link href="@Url.Content("~/Content/mystyle/")css/templatemo_style.css" rel='stylesheet' type='text/css'>

    <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
      <script src="https://oss.maxcdn.com/libs/respond.js/1.3.0/respond.min.js"></script>
    <![endif]-->

</head>
<body>

    @*<div class="templatemo-top-menu">*@
    <div class="container">
        <!-- Static navbar -->
        <div class="navbar navbar-default" role="navigation">
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>

                </div>
                <div class="navbar-collapse collapse" id="templatemo-nav-bar">
                    <ul class="nav navbar-nav navbar-right" style="margin-top: 0px;">
                        <li><a href="#templatemo-blog">اتصل بنا</a></li>
                        <li><a href="#templatemo-blog">بحث متخصص</a></li>
                        <li>@Html.ActionLink("الاقمار", "Satellite")</li>
                        <li>@Html.ActionLink("القنوات", "channel")</li>
                        <li>@Html.ActionLink("التصنيفات", "category")</li>
                        <li><a href="#about">عن الخدمه</a></li>
                        <li class="active">@Html.ActionLink("الرئيسيه", "Index")</li>

                    </ul>
                </div><!--/.nav-collapse -->
            </div><!--/.container-fluid -->
        </div><!--/.navbar -->
    </div> <!-- /container -->
    @*</div>*@












    <script src="@Url.Content("~/Content/mystyle/")js/jquery.min.js" type="text/javascript"></script>
    <script src="@Url.Content("~/Content/mystyle/")js/bootstrap.min.js" type="text/javascript"></script>
    <script src="@Url.Content("~/Content/mystyle/")js/stickUp.min.js" type="text/javascript"></script>
    <script src="@Url.Content("~/Content/mystyle/")js/colorbox/jquery.colorbox-min.js" type="text/javascript"></script>
    <script src="@Url.Content("~/Content/mystyle/")js/templatemo_script.js" type="text/javascript"></script>
    <!-- templatemo 395 urbanic -->
    <div>
        @RenderBody()
    </div>
</body>
</html>